controller_list:
  - name: PositionBased_PositionTrajectory_Controller
    action_ns: follow_joint_trajectory
    default: False
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  # - name: VelocityBased_PositionTrajectory_Controller
  #   action_ns: follow_joint_trajectory
  #   default: False
  #   type: FollowJointTrajectory
  #   joints:
  #     - joint_1
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6
  # - name: EffortBased_PositionTrajectory_Controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - joint_1
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6